import React from 'react';


export interface DetailedResultType{
    results: string[]; // list of results for each question
    finalResult: string; // general summary
    finalSentence: string; // final job title
    finalDeclaredFuture: string // fun stuff
    finalCareer: string // what they are going to do in future
    colorVibe: string, // color vibe   
}



function DetailedResult(finishedQuestion: DetailedResultType){
      return <div className="results-container">
        {/* Just like my heckin fortune!!! Shows a defined, simple, determined result */}
        <div className="final-career" style={{"color":finishedQuestion.colorVibe}}>
          {finishedQuestion.finalDeclaredFuture +"~~"+ finishedQuestion.finalCareer}
        </div>
        {/* Shows individual insights if finished loading */}
        <div className="results-list">
          <ul style={{ listStyleType: "none", paddingLeft: 0, margin: 0 }}>
            {finishedQuestion.results.map((res, i) => (
              <li key={i}>{res}</li>
            ))}
          </ul>
        </div>
        {/* Shows character analysis */}
        <div className="final-results">
          <h3>Character Analysis:</h3>
          <p>{finishedQuestion.finalResult}</p>
        </div>
        {/* Shows career prediction */}
        <div className="final-sentence">
          <h3>Overall Suggestion:</h3>
          <p>{finishedQuestion.finalSentence}</p>
        </div>
        {/*Makes user not do stupid stuff, (or more correctly, us less liable!)*/}
        <div className="ai-disclaimer">
            Generated by AI: All choices are yours, and the future is ultimately in your hands. Not responsible for any user damages.
        </div>
      </div>
}
export default DetailedResult