import React from 'react';
import { PreviousResultType } from '../../AIResultsContext';


export interface DetailedResultType{
    results: string[]; // list of results for each question
    finalResult: string; // general summary
    finalSentence: string; // final job title
    finalDeclaredFuture: string // fun stuff
    finalCareer: string // what they are going to do in future
    colorVibe: string, // color vibe
    date: string   
}
export interface BasicResultType{
  results: string[]; // list of results for each question
  finalResult: string; // general summary
  finalSentence: string; // final job title
  finalDeclaredFuture: string // fun stuff
  finalCareer: string // what they are going to do in future
  colorVibe: string, // color vibe   
  date: string
}



function PreviousResult(finishedQuestion: PreviousResultType){
      return <div className="results-container">
      
        {/* Just like my heckin fortune!!! Shows a defined, simple, determined result */}
        <div className="final-career" style={{"color":finishedQuestion.colorVibe}}>
          {finishedQuestion.finalDeclaredFuture +"~~"+ finishedQuestion.finalCareer}
        </div>
        {/* Shows individual insights if finished loading */}
        <div className="results-list">
          <ul style={{ listStyleType: "none", paddingLeft: 0, margin: 0 }}>
            {finishedQuestion.results.map((res: string, i: number) => (
              <li key={i}>{res}</li>
            ))}
          </ul>
        </div>
        {/* Shows character analysis */}
        <div className="final-results">
          <h3>Character Analysis:</h3>
          <p>{finishedQuestion.finalResult}</p>
        </div>
        {/* Shows career prediction */}
        <div className="final-sentence">
          <h3>Overall Suggestion:</h3>
          <p>{finishedQuestion.finalSentence}</p>
        </div>
        <div className="date">Achieved at: {finishedQuestion.date}</div>
        {/*Makes user not do stupid stuff, (or more correctly, us less liable!)*/}
        <div className="ai-disclaimer">
          <div>"I THINK THEREFORE I AM!" You think your own thoughts, not the AI, and therefore you act your own actions</div>
          <div>Generated by AI: All choices are yours, and the future is ultimately in your hands. Not responsible for any user damages.</div>
        </div>
      </div>
}
export default PreviousResult